export const initialState = {
  items: [
    {
      id: "What_ajjaa",
      user_id: "A",
      link: "add_tags_for_solutions",
      title: "Add tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "Enhancement",
      vote: 17,
      voted: false,
      status: "suggestion",
      comments: [
        {
          id: "abcd_abc",
          user_name: "11gg Moss",
          avatar: "image-jay.jpg",
          user_id: "@hexagon.bestagon",
          comment: "this is comment",
          replies: [
            {
              id: "zAcds_as",
              user_name: "1-1Georrge random",
              avatar: "image-george.jpg",
              user_id: "@george.johnson",
              comment: "this is another  comment comment",
            },
            {
              id: "sadio_ASD",
              user_name: "1-2james dulex",
              avatar: "image-jay.jpg",
              user_id: "@james.christina",
              comment: "comment comment comment",
            },
            {
              id: "sadio_GG",
              user_name: "1-2james dulex",
              avatar: "image-jay.jpg",
              user_id: "@james.christina",
              comment: "This is not a comment",
            },
          ],
        },
      ],
    },
    {
      id: "asd_asdASD",
      user_id: "B",
      link: "2_tags_for_solutions",
      title: "2 tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "UI",
      vote: 22,
      voted: false,
      status: "suggestion",
      comments: [
        {
          id: "gh_asdASDds",
          user_name: "22gg Moss",
          avatar: "image-george.jpg",
          user_id: "@hexagon.bestagon",
          comment: "this is comment",
          replies: [
            {
              id: "AcasA_sdjsd",
              user_name: "2-1Georrge random",
              avatar: "image-george.jpg",
              user_id: "@george.johnson",
              comment: "this is another  comment comment",
            },
            {
              id: "OVP_JQIsasd",
              user_name: "2-2james dulex",
              avatar: "image-james.jpg",
              user_id: "@james.christina",
              comment: "comment comment comment",
            },
          ],
        },
      ],
    },
    {
      id: "asdisdAa_jdjf",
      user_id: "C",
      link: "3_tags_for_solutions",
      title: "3 tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "UX",
      vote: 19,
      voted: false,
      status: "suggestion",
      comments: [
        {
          id: "asdjvn_fdn",
          user_name: "33gg Moss",
          avatar: "image-george.jpg",
          user_id: "@hexagon.bestagon",
          comment: "this is comment",
          replies: [
            {
              id: "FsdADaf",
              user_name: "3-2james dulex",
              avatar: "image-james.jpg",
              user_id: "@james.christina",
              comment: "comment comment comment",
            },
          ],
        },
      ],
    },
    {
      id: "What_acxvDSa",
      user_id: "D",
      link: "4_tags_for_solutions",
      title: "4 tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "Bug",
      vote: 44,
      voted: false,
      status: "suggestion",
      comments: [
        {
          id: "dsds_asdFG",
          user_name: "44gg Moss",
          avatar: "image-george.jpg",
          user_id: "@hexagon.bestagon",
          comment: "this is comment",
          replies: [
            {
              id: "dsds_asdAQ",
              user_name: "4-1Georrge random",
              avatar: "image-george.jpg",
              user_id: "@george.johnson",
              comment: "this is another  comment comment",
            },
            {
              id: "dsds_asdbas",
              user_name: "4-1Georrge random",
              avatar: "image-george.jpg",
              user_id: "@george.johnson",
              comment: "this is another  comment comment",
            },
            {
              id: "dsds_asdvbA",
              user_name: "4-2james dulex",
              avatar: "image-james.jpg",
              user_id: "@james.christina",
              comment: "comment comment comment",
            },
          ],
        },
      ],
    },
    {
      id: "What_acxvDaaSda",
      user_id: "D",
      link: "6_tags_for_solutions",
      title: "6 tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "Bug",
      vote: 75,
      voted: false,
      status: "live",
      comments: [],
    },
    {
      id: "What_agds4aSda",
      user_id: "g",
      link: "5_tags_for_solutions",
      title: "5 tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "Bug",
      vote: 23,
      voted: false,
      status: "in-progress",
      comments: [],
    },
    {
      id: "What_ag88da",
      user_id: "f",
      link: "7_tags_for_solutions",
      title: "7 tags for solutions",
      detail: "Easier to search23322 for solutions based on a specific stack.",
      category: "Feature",
      vote: 82,
      voted: false,
      status: "planned",
      comments: [],
    },
  ],
};
