export const initialState = {
  items: [
    {
      user_id: "A",
      link: "Add_tags_for_solutions",
      title: "Add tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "Enhancement",
      vote: 17,
      voted: false,
      comments: [
        {
          id: 1,
          user_name: "11gg Moss",
          avatar: "image-jay.jpg",
          user_id: "@hexagon.bestagon",
          comment: "this is comment",
          replies: [
            {
              id: 1,
              user_name: "1-1Georrge random",
              avatar: "image-george.jpg",
              user_id: "@george.johnson",
              comment: "this is another  comment comment",
            },
            {
              id: 2,
              user_name: "1-2james dulex",
              avatar: "image-jay.jpg",
              user_id: "@james.christina",
              comment: "comment comment comment",
            },
          ],
        },
      ],
    },
    {
      user_id: "B",
      link: "2_tags_for_solutions",
      title: "2 tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "UI",
      comments: [
        {
          id: 2,
          user_name: "22gg Moss",
          avatar: "image-george.jpg",
          user_id: "@hexagon.bestagon",
          comment: "this is comment",
          replies: [
            {
              id: 1,
              user_name: "2-1Georrge random",
              avatar: "image-george.jpg",
              user_id: "@george.johnson",
              comment: "this is another  comment comment",
            },
            {
              id: 2,
              user_name: "2-2james dulex",
              avatar: "image-james.jpg",
              user_id: "@james.christina",
              comment: "comment comment comment",
            },
          ],
        },
      ],
      vote: 22,
      voted: false,
    },
    {
      user_id: "C",
      link: "3_tags_for_solutions",
      title: "3 tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "UX",
      comments: [
        {
          id: 3,
          user_name: "33gg Moss",
          avatar: "image-george.jpg",
          user_id: "@hexagon.bestagon",
          comment: "this is comment",
          replies: [
            {
              id: 1,
              user_name: "3-1Georrge random",
              avatar: "image-george.jpg",
              user_id: "@george.johnson",
              comment: "this is another  comment comment",
            },
            {
              id: 2,
              user_name: "3-2james dulex",
              avatar: "image-james.jpg",
              user_id: "@james.christina",
              comment: "comment comment comment",
            },
          ],
        },
      ],
      vote: 19,
      voted: false,
    },
    {
      user_id: "D",
      link: "4_tags_for_solutions",
      title: "4 tags for solutions",
      detail: "Easier to search for solutions based on a specific stack.",
      category: "Bug",
      comments: [
        {
          id: 4,
          user_name: "44gg Moss",
          avatar: "image-george.jpg",
          user_id: "@hexagon.bestagon",
          comment: "this is comment",
          replies: [
            {
              id: 1,
              user_name: "4-1Georrge random",
              avatar: "image-george.jpg",
              user_id: "@george.johnson",
              comment: "this is another  comment comment",
            },
            {
              id: 2,
              user_name: "4-2james dulex",
              avatar: "image-james.jpg",
              user_id: "@james.christina",
              comment: "comment comment comment",
            },
          ],
        },
      ],
      vote: 44,
      voted: false,
    },
  ],
};
